#!/bin/bash

## Easier navigation
alias ~="cd ~"
alias ..="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cd4="cd ../../../.."
alias cd5="cd ../../../../.."
alias h="cd ~ && clear"


## Easier lists files: ls, ls -al, etc
# alias ls="ls --color=tty"
alias l="ls -Alh --group-directories-first"
alias ll="ls -lh --group-directories-first"
alias la="ls -alh --group-directories-first"
alias ld="ls -Alhd */" # only directories


## Easier common functions
alias q="exit"                          # exit terminal
alias c="clear"                         # clear terminal
alias cl="clear && l"                   # clear terminal and show list FILEs
alias add="sudo apt-get install"        # shorthand apt-get install
alias f5="refresh"                      # load source
alias where="which"


## Disable default keyboard
alias dk="xinput float $(xinput list|grep AT|grep id=|cut -f 2|cut -f 2 -d =)"

## remaps and switch keyboard
alias kbmap:caps_esc="setxkbmap -option caps:swapescape"


## edit files
alias @hosts="sudo vim /etc/hosts"  # edit hosts file
alias @vim="vim ~/.vimrc"           # edit vimrc file
alias @zsh="vim ~/.zshrc"           # edit zshrc file


## Networking. IP address, dig, DNS
alias ipnet="dig +short myip.opendns.com @resolver1.opendns.com"
# alias dig="dig +nocmd any +multiline +noall +answer"
# wget sucks with certificates. Let's keep it simple.
# alias wget="curl -O"


## NPM shorthand command
alias ni="npm install"
alias nis="npm install --save"
alias nid="npm install --save-dev"
alias nig="npm install --global"
alias nt="npm test"
alias nit="npm install && npm test"
alias nk="npm link"
alias nr="npm run"
alias nf="npm cache clean && rm -rf node_modules && npm install"
alias nlg="npm list --global --depth=0"
alias npr="npm prune"
alias nrb="npm run build"
alias ncc="npm cache clean"


## php laravel command
alias art="php artisan"
alias serve="php artisan serve"
alias tinker="php artisan tinker"
