#!/bin/bash

## export vim as default editor
export EDITOR="vim"

## User font directory
export FONTS_DIR="$HOME/.local/share/fonts"

## This loads nvm
export NVM_DIR="$HOME/.nvm"


##
## Add and export PATH here...
##

## set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:$HOME/bin"
fi

## Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

## Dropbox PATH
export PATH="$PATH:$HOME/.dropbox-bin"

## Composer PATH
export PATH="$PATH:$HOME/.config/composer/vendor/bin"

## Handling Ruby with RVM
##    Load RVM into a shell session *as a function*
[ -s "$HOME/.rvm/scripts/rvm" ] && source "$HOME/.rvm/scripts/rvm"

## Handling NodeJS with NVM
##    Node Version Manager
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
