#!/bin/bash

##
## Easier navigation
##
alias ~="cd ~"
alias ..="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cd4="cd ../../../.."
alias cd5="cd ../../../../.."
alias h="cd ~ && clear"

##
## Easier lists files: ls, ls -al, etc
##
# alias ls="ls --color=tty"
alias l="ls -Alh --group-directories-first"
alias ll="ls -lh --group-directories-first"
alias la="ls -alh --group-directories-first"
alias ld="ls -Alhd */" # only directories

##
## Easier common functions
##
alias q="exit" # exit terminal
alias c="clear" # clear terminal
alias cl="clear && la" # clear terminal and show list FILEs
alias add="sudo apt-get install" # shorthand apt-get install
alias f5="refresh" # load source
alias where="which" # :)
alias was="echo '\x1Bc'" # deep clean terminal

##
## Disable default keyboard
##
alias dk="xinput float $(xinput list | grep AT | grep id= | cut -f 2 | cut -f 2 -d =)"

##
## swapping escape to capslock
##
alias kbmap:caps_esc="setxkbmap -option caps:swapescape"

##
## edit files
##
alias @hosts="sudo $EDITOR /etc/hosts" # edit hosts file
alias @vim="$EDITOR $HOME/.vimrc" # edit vimrc file
alias @zsh="$EDITOR $HOME/.zshrc" # edit zshrc file

##
## Networking. IP address, dig, DNS
##
alias ipnet="dig +short myip.opendns.com @resolver1.opendns.com"
# alias dig="dig +nocmd any +multiline +noall +answer"
# wget sucks with certificates. Let's keep it simple.
# alias wget="curl -O"

##
## NPM shorthand command
##
alias ni="npm install"
alias nis="npm install --save"
alias nid="npm install --save-dev"
alias nig="npm install --global"
alias nt="npm test"
alias nit="npm install && npm test"
alias nk="npm link"
alias nr="npm run"
alias nf="npm cache clean --force && rm -rf node_modules && npm install"
alias nlg="npm list --global --depth=0"
alias npr="npm prune"
alias ncc="npm cache clean --force"
alias nrb="npm run build"
alias nrs="npm run start"

##
## Yarn shorthand command
##
alias yas="yarn add"
alias yad="yarn add --dev"
alias yag="yarn global add"
alias yf="yarn cache clean && rm -rf yarn.lock node_modules && yarn install"
alias yrl="rm yarn.lock"
alias ycc="yarn cache clean"

##
## php laravel command
##
alias art="php artisan"
alias tinker="php artisan tinker"
alias art:f5="php artisan clear-compiled && php artisan cache:clear && php artisan view:clear && php artisan optimize"

##
## PHP unit
##
alias p="phpunit"

##
## Python Server
##
alias py-serve="python -m SimpleHTTPServer$@"

##
## Git
##
alias nah="git reset --hard; git clean -df"
