#!/bin/bash

DOT_FILES="$HOME/.dotfiles/autoload"
DOT_EXTRA="$HOME/.dotfiles/extra"

## secret key

## environment PATH
load_source "$DOT_FILES/workspace"

## function
load_source "$DOT_FILES/function"

## aliases
load_source "$DOT_FILES/aliases"

## Extra files
for __filepath in $DOT_EXTRA/.* $DOT_EXTRA/*; do
	if [[ ! "$(basename $__filepath)" =~ ^(.example|.gitignore) ]]; then
		load_source "$__filepath"
	fi

	unset __filepath
done
