#!/bin/bash

## Locale
# export LANG="en_US.UTF-8"
# export LANGUAGE="en_US.UTF-8"
# export LC_ALL="en_US.UTF-8"
# export LC_COLLATE="C"
# export LC_CTYPE="en_US.UTF-8"
# export LC_TIME="en_US.UTF-8"

## User Registry
export AUTHOR_NAME="Guntur Poetra"
export AUTHOR_EMAIL="poetra.guntur@gmail.com"
export AUTHOR_WEBSITE="https://gunturpoetra.com"
export AUTHOR_GITHUB_URL="https://github.com/iguntur"

## export vim as default editor
# export EDITOR="vim"
export EDITOR="nvim"

## User font directory
# export FONTS_DIR="$HOME/.local/share/fonts"

################################################################################
# export PATH="$PATH:$HOME/.local/bin"

export TZ="Asia/Makassar"
export HOME_SSH="${HOME}/.ssh"
