#!/bin/bash

## User Registry
export AUTHOR_NAME="Guntur Poetra"
export AUTHOR_EMAIL="poetra.guntur@gmail.com"
export AUTHOR_GITHUB_URL="https://github.com/iguntur"

## export vim as default editor
export EDITOR="vim"

## User font directory
export FONTS_DIR="$HOME/.local/share/fonts"

################################################################################

## Go
# if [ -f "$(which go)" ]; then
# 	export PATH="$PATH:/usr/local/go/bin"
# 	export GOPATH="$(go env GOPATH)"
# 	export PATH="$PATH:$GOPATH/bin"
# fi


## Dropbox
export PATH="$PATH:$HOME/.dropbox-bin"


## Java
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$JAVA_HOME/db/bin"
export PATH="$PATH:$JAVA_HOME/jre/bin"
export PATH="$PATH:$HOME/.local/apache-maven/apache-maven-3.3.9/bin" # maven


## Android and stuff
## The React Native command line interface requires the "ANDROID_HOME" environment variable to be set up.
## https://facebook.github.io/react-native/docs/getting-started.html#3-configure-the-android-home-environment-variable
export ANDROID_HOME="$HOME/Android/Sdk"
export PATH="$PATH:$ANDROID_HOME/tools"
#export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_HOME/platform-tools"


## NPM (NodeJS)
export NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin" # global npm package


## Rust (cargo)
export PATH="$PATH:$HOME/.cargo/bin"


## n (Node Version Manager)
export N_PREFIX="$HOME/.local/share/node-version-manager"
export PATH="$PATH:$N_PREFIX/bin"


## PHP composer
export PATH="$PATH:$HOME/.config/composer/vendor/bin" # global packagist
