#!/bin/bash

##
## Load our dotfiles
##   Use it to configure your PATH, this it being first in line.
##
[ -f "$HOME/.autoload/main" ] && source "$HOME/.autoload/main"

# Install nvm from aur repo.
# yay -S nvm
[ -f "/usr/share/nvm/init-nvm.sh" ] && source "/usr/share/nvm/init-nvm.sh"

##
## more options here...
##

# opam configuration
test -r ${HOME}/.opam/opam-init/init.zsh && . ${HOME}/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true


# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=$HOME/.cache/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

[[ -r "/usr/share/z/z.sh" ]] && source /usr/share/z/z.sh
