#!/bin/bash

##
## Load our dotfiles
##   Use it to configure your PATH, this it being first in line.
##
[ -f "$HOME/.autoload/main" ] && source "$HOME/.autoload/main"

##
## more options here...
##

# opam configuration
test -r ${HOME}/.opam/opam-init/init.zsh && . ${HOME}/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
