#!/bin/bash

source "$HOME/.dotfiles/global-def"

################################################################################
# Dotfiles Bin
################################################################################
export PATH="$PATH:$DF_PATH/bin"
export PATH="$PATH:$DF_PATH/extra/.bin"

################################################################################
## Load our dotfiles
## Use it to configure your PATH, this it being first in line.
################################################################################
load_source "$HOME/.dotfiles/autoload/main"

## Software Development KIT (SDK)
load_source "$HOME/.dotfiles/sdkrc"

## Shell Environment and Productivity Tools
load_source "$HOME/.dotfiles/shellrc"

################################################################################
# more options here...
################################################################################
