#!/bin/bash

source "$HOME/.dotfiles/global-def"

###

base_dir="$(cd $(dirname $0) && pwd)"

dotfiles_links=(
	## Shell
	"bash_profile"
	"bashrc"
	"zshrc"
	## Git
	"gitconfig"
	"gitignore"
	"gitattributes"
	## Terminal Editor
	# "vim"
	# "vimrc"
	# "tmux.conf"
)

dotfiles_files=(
	".npmrc"
)

create_symlink() {
	for __filename in ${dotfiles_links[@]}; do
		SOURCE="$base_dir/$__filename"
		DEST="$HOME/.$__filename"

		if [ "$1" == "-y" ]; then
			ln -fsnv "$SOURCE" "$DEST"
		else
			ln -isnv "$SOURCE" "$DEST"
		fi
	done
	unset __filename
}

remove_symlink() {
	for __filename in ${dotfiles_links[@]}; do
		__filepath="$HOME/.$__filename"

		if [ -e "$__filepath" ] && [ -L "$__filepath" ]; then
			if [ "$1" == "-y" ]; then
				rm -v "$__filepath"
			else
				rm -i -v "$__filepath"
			fi
		fi
	done
	unset __filename
	unset __filepath
}

copy_files() {
	for __filename in ${dotfiles_files[@]}; do
		cp "$base_dir/files/$__filename" "$HOME/$__filename"
	done
	unset __filename
}

remove_files() {
	for __filename in ${dotfiles_links[@]}; do
		rm "$HOME/$__filename"
	done
	unset __filename
}

setup_config_links() {
	for __config_path in $base_dir/config/*; do
		SOURCE="$__config_path"
		DEST="$HOME/.config/$(basename $__config_path)"

		if [ "$1" == "-y" ]; then
			ln -fsnv "$SOURCE" "$DEST"
		else
			ln -isnv "$SOURCE" "$DEST"
		fi
	done
	unset __config_path
}

case $1 in
install-files)
	shift
	copy_files "$@"
	;;
install-config)
	shift
	setup_config_links "$@"
	;;
install-symlinks)
	shift
	create_symlink "$@"
	;;
clean-all)
	shift
	remove_symlink "$@"
	remove_files
	;;
*)
	echo "  ./setup <command> [options]"
	echo
	echo "  Commands:"
	echo "    install-files            Copy static files"
	echo "    install-config           Create config symlinks"
	echo "    install-symlinks         Create all dotfiles symlinks"
	echo "    clean-all                Remove all dotfiles symlinks"
	echo
	echo "  Options:"
	echo "      -y                     Prevent prompt"
	;;
esac

exit 0
