#!/bin/bash

source "$HOME/.dotfiles/global-def"

###

progName="$(basename $0)"
base_dir="$(cd $(dirname $0) && pwd)"

dotfiles_links=(
	## Shell
	"bash_profile"
	"bashrc"
	"zshrc"
	## Terminal Editor
	"tmux.conf"
	"condarc"
	"tigrc"
)

dotfiles_files=(
	".npmrc"
)

config_dirs=(
	git
	# "alacritty"
)

create_symlink() {
	for __filename in ${dotfiles_links[@]}; do
		SOURCE="$base_dir/$__filename"
		DEST="$HOME/.$__filename"

		if [ "$1" == "-y" ]; then
			ln -fsnv "$SOURCE" "$DEST"
		else
			ln -isnv "$SOURCE" "$DEST"
		fi
	done
	unset __filename
}

remove_symlink() {
	for __filename in ${dotfiles_links[@]}; do
		__filepath="$HOME/.$__filename"

		if [ -e "$__filepath" ] && [ -L "$__filepath" ]; then
			if [ "$1" == "-y" ]; then
				rm -v "$__filepath"
			else
				rm -i -v "$__filepath"
			fi
		fi
	done
	unset __filename
	unset __filepath
}

copy_files() {
	for __filename in ${dotfiles_files[@]}; do
		cp "$base_dir/files/$__filename" "$HOME/$__filename"
	done
	unset __filename
}

remove_files() {
	for __filename in ${dotfiles_links[@]}; do
		rm "$HOME/$__filename"
	done
	unset __filename
}

setup_config_links() {
	for __config_path in ${config_dirs[@]}; do
		SOURCE="$base_dir/config/$__config_path"
		DEST="$HOME/.config/$(basename $__config_path)"

		if [ "$1" == "-y" ]; then
			ln -fsnv "$SOURCE" "$DEST"
		else
			ln -isnv "$SOURCE" "$DEST"
		fi
	done
	unset __config_path
}

__print_usage() {
	cat <<-HEREDOC
		   Usage: $progName <command> [options]

		   Command:
		     install-files            Copy static files
		     install-config           Create config symlinks
		     install-symlinks         Create all dotfiles symlinks
		     clean-all                Remove all dotfiles symlinks

		   Options:
		       -h, --help             Show this message and exit
		       -y                     Prevent prompt

	HEREDOC
}

case $1 in
install-files)
	shift
	copy_files "$@"
	;;
install-config)
	shift
	setup_config_links "$@"
	;;
install-symlinks)
	shift
	create_symlink "$@"
	;;
clean-all)
	shift
	remove_symlink "$@"
	remove_files
	;;
-h | --help | *)
	__print_usage
	exit 0
	;;
esac

exit 0
