#!/bin/bash

##
## Shell Environment and Productivity Tools
## - CLI completions and plugins
## - Developer Tools and service integrations
##

################################################################################
# FZF
################################################################################
# Setting fd as the default source for fzf
# Now fzf (w/o pipe) will use fd instead of find
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS='--height 100% --layout=reverse --inline-info'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export FZF_CTRL_T_OPTS="--preview '(highlight -t 4 -I -l -O ansi {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -500'"
export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"

# To apply the command to ALT-C as well
# export FZF_ALT_C_OPTS="--exclude .git"

load_source "${HOME}/.fzf.$SHELL_NAME"

################################################################################
# Z (easy jump into directory)
################################################################################
load_source "$(brew --prefix)/etc/profile.d/z.sh"

################################################################################
# Github CLI
################################################################################
if cmd_exists gh; then
	case $SHELL_NAME in
	bash) source <(gh completion --shell bash) ;;
	zsh) source <(gh completion --shell zsh) ;;
	esac
fi

################################################################################
# Docker
## brew install docker-completion docker-compose-completion
################################################################################

################################################################################
# Kubernetes
################################################################################
# if cmd_exists minikube; then
# 	case $SHELL_NAME in
# 		bash) source <(minikube completion bash);;
# 		zsh) source <(minikube completion zsh);;
# 	esac
# fi

# if cmd_exists kubectl; then
# 	case $SHELL_NAME in
# 		bash) source <(kubectl completion bash);;
# 		zsh) source <(kubectl completion zsh);;
# 	esac
# fi

################################################################################
# Google Cloud Platform
################################################################################
# The next line updates PATH for the Google Cloud SDK.
load_source "/Users/guntur/Env/google-cloud-sdk/path.$SHELL_NAME.inc"

# The next line enables shell command completion for gcloud.
load_source "/Users/guntur/Env/google-cloud-sdk/completion.$SHELL_NAME.inc"

################################################################################
# Heroku - autocomplete setup
################################################################################
# if [ $SHELL_NAME = "zsh" ]; then
# 	HEROKU_AC_ZSH_SETUP_PATH=$HOME/.cache/heroku/autocomplete/zsh_setup
# 	load_source $HEROKU_AC_ZSH_SETUP_PATH
# fi

################################################################################
# Powerline Fonts
################################################################################
# if [ $SHELL_NAME = "zsh" ]; then
# 	load_source "/usr/share/zsh/site-contrib/powerline.zsh"
# fi

################################################################################
# Dotfiles Bin
################################################################################
export PATH="$PATH:$DF_PATH/bin"

################################################################################
# Dropbox
################################################################################
# export PATH="$PATH:$HOME/.dropbox-bin"
