#!/bin/bash

# Setting fd as the default source for fzf
# Now fzf (w/o pipe) will use fd instead of find
export FZF_DEFAULT_COMMAND='fd --type f'

export FZF_DEFAULT_OPTS='--height 60%'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_CTRL_T_OPTS="--preview '(highlight -t 4 -I -l -O ansi {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -500'"
