#!/bin/bash

# Setting fd as the default source for fzf
# Now fzf (w/o pipe) will use fd instead of find
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS='--height 100% --layout=reverse --inline-info'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export FZF_CTRL_T_OPTS="--preview '(highlight -t 4 -I -l -O ansi {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -500'"
export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"

# To apply the command to ALT-C as well
# export FZF_ALT_C_OPTS="--exclude .git"


GATSBY_TELEMETRY_DISABLED=1
