#!/bin/bash

__safe_check_git_project() {
	set -e

	project_dir="$(pwd)"

	# Check if is ".git" directory exists
	if [ ! -d "$project_dir/.git" ]; then
		echo "fatal: \".git\" directory not found"
		git status
		exit 128
	fi

	# Check if is git directory
	if ! git rev-parse --git-dir >/dev/null 2>&1; then
		git rev-parse --git-dir
		exit 128
	fi

	# Check if is inside git work tree
	if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		git status
		exit 128
	fi
}
