# ubuntu command
alias q="exit"
alias remove="rm -rf"

# laravel command
alias art="php artisan"
alias serve="php artisan serve"
alias tinker="php artisan tinker"
alias reload="php artisan cache:clear && php artisan view:clear && php artisan optimize && php artisan serve --host=javastudio.dev"

# VIM Config
alias vimconf="vim ~/.vimrc"

# php
alias php:serve="php -S 127.0.0.1:8000 -t public"

# Apache Server
alias restart:apache="sudo service apache2 restart"
alias restart:mysql="sudo service mysql restart"
